### ISSUE TITLE
Training data missing

### ISSUE THREAD

**Issue by brobertson** [WenmuZhou/crnn.gluon#2]
Thanks for posting this example. It is most helpful.

I wonder if you might consider also adding some sample training data and data files to this project, such as those in the default files /data/zhy/crnn/Chinese_character/test2.txt and /data/zhy/crnn/Chinese_character/train2.txt. This would make it much easier for someone like me who would like to adopt your excellent project to his or her own needs.

**Comment by WenmuZhou** [comment]
the dataset I used is not a public dataset, you can generate some data according to [readme](https://github.com/WenmuZhou/crnn.gluon/blob/master/README.md) and [this code](https://github.com/WenmuZhou/crnn.pytorch/tree/master/data_generator)
