### ISSUE TITLE
不定长输入的训练和推理

### ISSUE THREAD

**Issue by lironghua318** [WenmuZhou/crnn.gluon#4]
1.请问模型是否支持不定长输入的训练和推理？
2.训练收敛时间是多长，我自己复现了一版遇到了收敛慢，acc一直为0，看你在别的回答中提到30epochs会收敛,收敛的时候loss大概是什么数量级的
3.另外symbol版的一个epoch可收敛，为什么gluon版的很慢
谢谢

**Comment by WenmuZhou** [comment]
1. 模型支持不定长的推理，但是训练还是定长的
2. 在我的数据集上收敛需要半天左右，loss记得不清楚了，应该是0.005
3. 我感觉gluon版本速度还可以

**Comment by lironghua318** [comment]
1.但是看到代码训练和推理都是强行resize到固定wh的？支持不定长的意思是先resize再做计算吗
2.数据集的数量级大概是什么样的，我的是百万级的，图片做了归一化处理收敛极慢，18epochs的loss大概在0.3左右，数据集比较大，训练时间很长了，是有什么坑吗，同样的数据集用symbol版实现，一个epoch的acc就收敛差不多了
非常感谢

**Comment by WenmuZhou** [comment]
1. 推理部分的resize只对小于制定长度的进行了resize到之后的pad
3. 数据集70w左右

**Comment by lironghua318** [comment]
最近又梳理了代码发现收敛慢以及acc一直为0 的原因是，最后网络输出的类别多加了1，标注也多了1
symbol，默认空白补0,所以标注索引要从1开始，类别也是在字典的基础上加1
gluon，写死了是空白补’-1‘，所以标注索引从0开始，类别也是字典长度就可以
因为在symbol基础上写的gluon版，因为这个问题卡了好久

**Comment by lironghua318** [comment]
分享之前自己实现的版本不收敛的原因
symbol lable 0代表blank，标注索引要从1开始
gluon 写死了是-1代表blank，就是字典的最后一位，索引从0开始就行
最后全连接的类别输出都是字典长度+1（blank）
