### ISSUE TITLE
accuracy is zero even after 640 epochs

### ISSUE THREAD

**Issue by BackT0TheFuture** [WenmuZhou/crnn.gluon#5]
Hi,
   I was trying training some OCR task,  but the acc is always zero .
the dataset is  [ICDAR2013 ](http://dagdata.cvc.uab.es/icdar2013competition/?ch=2)
It's just alphabet and number and common characters. I created  one charset as below.

> all_english = no + """abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ,.<>/?;:"[]{}!@#$%^&*()-=+\|""" + BLANK_SYMBOL

the GT file is like something below

```
./data/test/word_1.png|||PROPER
./data/test/word_2.png|||FOOD
./data/test/word_3.png|||PRONTO
./data/test/word_4.png|||professional
./data/test/word_5.png|||Java
./data/test/word_6.png|||Web
./data/test/word_7.png|||Services
./data/test/word_8.png|||go
./data/test/word_9.png|||SONY
```

and I modified the [line 28](https://github.com/WenmuZhou/crnn.gluon/blob/master/dataset.py#L28) code in dataset.py 

`line = line.strip('\n').split('|||')`

the attached file is traning log.

[train.zip](https://github.com/WenmuZhou/crnn.gluon/files/2944230/train.zip)

**Comment by BackT0TheFuture** [comment]
my bad.

**Comment by winsonxxxx** [comment]
Hi, goodtogood. Do you solve the problem? What is wrong with the zero acc? I also meet this problem, too.

**Comment by ghost** [comment]
@goodtogood what was the solution?
