### ISSUE TITLE
代码无误，但是loss一直很高

### ISSUE THREAD

**Issue by whitecooper** [WenmuZhou/crnn.gluon#6]
您好，我参考了您的代码，使用自己生成的英文数据集进行训练，loss一直在100多，无法下降，请问这是您跑过的效果好的代码嘛

**Comment by WenmuZhou** [comment]
这个是我调整的最好的代码，这个是可以确定的，你检查下数据

**Comment by whitecooper** [comment]
嗯嗯，我把数据简化之后，测试集acc到了0.95。但是如果我一副图片是5个单词，单词之间用空格隔开的话，效果就会像原来一样，loss一直很高。是我的数据处理有问题吗，我的alphabet把单词之间的空格去掉了，比如图片内容是111 222 333 aaa bbb我的alphabet是123ab，在encode时候，也 做了label = label.replace(' ', '')这样处理。

**Comment by WenmuZhou** [comment]
这样可能是空格和背景不能很好的区分造成的

**Comment by whitecooper** [comment]
那也就是说，我不需要在alphabet里面加入‘ ’是吗？我看您的alphabet里面就没有空格。

**Comment by WenmuZhou** [comment]
是的

**Comment by whitecooper** [comment]
好的，麻烦您了。我再去看看。

**Comment by whitecooper** [comment]
还有个问题哈，CRNN对于中文的识别比英文差好多啊。英文的test_acc可以到95，但是中文的也就到50.您当时也是这样吗？还是中英文其实差不多

**Comment by WenmuZhou** [comment]
中文字符数量多，对数据集要求的比较多，英文的相对学习起来比较简单

**Comment by whitecooper** [comment]
那我把数据集增加到一定数量，中文的识别也是可以不错的吧？

**Comment by WenmuZhou** [comment]
中文一直是个痛点，理论上来说，数据集上去了，准确率也会上去

**Comment by whitecooper** [comment]
好的好的，您有博客什么的嘛？很喜欢您的代码风格，同时我最近也是接触OCR和gluon，如果有的话，麻烦告知一下，想关注一下。

**Comment by WenmuZhou** [comment]
我比较少写博客，给你个知乎吧，https://www.zhihu.com/people/wenmu_zj/activities
