### ISSUE TITLE
辨识垂直的文字，需要做什么调整吗？

### ISSUE THREAD

**Issue by stereomatchingkiss** [WenmuZhou/crnn.gluon#8]
paper上说这个模型是为了水平方向的文字而设计的，如果我们要辨识垂直的文字，该做何种调整呢？

1. 不用理他
2. 修改网路结构
3. 制造出垂直的文字串，然后旋转90度

**Comment by WenmuZhou** [comment]
我觉得第三种好一点

**Comment by stereomatchingkiss** [comment]
谢谢，有机会尝试的话，我会回报结果的
